
# Where the main url for the Humdurm notation plugin exists:
notationurl: /scripts/humdrum-notation-plugin.js
#notationurl: https://plugin.humdrum.org/scripts/humdrum-notation-plugin.js

#humdrumjsurl: https://js.humdrum.org/scripts/humdrum.js
#humdrumurl: /scripts/humdrum.js


